### PR TITLE
Fixed bugs in rest.py

### PR DESCRIPTION
**Pull request by ka7eh**
- Updated 'import decimal'
- Fixed call to '_default_decimal' method

### CODE REVIEW

**Comment by mach-kernel** [comment]
Hey! I think I beat you to it. I ran the unit tests and it choked so I did the same thing. I hope you don't mind if I close this? :+1:

**Comment by ka7eh** [comment]
No problemo. Go for it. :)

**Comment by mach-kernel** [comment]
:100:

**Comment by ka7eh** [comment]
Forgot to mention: there was another bug fix in this PR for accessing '_default_decimal'; it must be either 'self._default_decimal' or 'Rest._default_decimal'.

**Comment by mach-kernel** [comment]
@ka7eh,

already taken care of! :) pushing it in a few, wrote some more tests for a few things but didn't push out the commits yet. thank you so much though I super appreciate it :)

**Comment by ka7eh** [comment]
:+1:

**Pull request closed without merging**
