### PR TITLE
transaction endpoint bug fix

### PR DESCRIPTION
**Pull request by ankitpopli1891**
the current endpoint returns 404 status code.

### CODE REVIEW

**Comment by mach-kernel** [comment]
I see that the postnomial forwardslash is causing some issues on some endpoints but not others. I'm going to go through the library and mend this anywhere else I notice a similar issue.

Thanks for the heads up. I will close the PR if there are other similar cases within the code but merge it if it is the only one, sound OK? :)

David

**Comment by ankitpopli1891** [comment]
Ya sure, no issues. :)

**Comment by mach-kernel** [comment]
@ankitpopli1891,

I pushed out a bugfix. You can get it from PyPi :)

**Comment by ankitpopli1891** [comment]
Thanks. 

I'm working on [python3 fork](https://github.com/ankitpopli1891/dwolla-python3) for it which I'll have to update as well.

Are you guys planning to support python3 in near future?

Ankit

**Pull request closed without merging**
